name: Run Python script on push

on:
  push:
    branches:
      - main  # Ganti dengan nama branch Anda jika perlu

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Ganti dengan versi Python yang Anda butuhkan

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ganti dengan nama file requirements Anda jika perlu

    - name: Run Python script
      run: python path/to/your_script.py  # Ganti dengan jalur menuju skrip Python Anda
